apiVersion: apps/v1
kind: Deployment
metadata:
  name: geospatial-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geospatial-service
  template:
    metadata:
      labels:
        app: geospatial-service
    spec:
      containers:
        - name: geospatial-service
          image: geospatial-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: WEATHER_SERVER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: geospatial-service
                  key: WEATHER_SERVER_ADDRESS
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: geospatial-service
                  key: WEATHER_API_KEY
